server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/igirepay_gateway?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
